# Generated by Django 5.0.3 on 2024-04-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО')),
                ('nick_name', models.CharField(db_index=True, max_length=50, verbose_name='Ник')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, null=True)),
                ('email_address', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name_plural': 'Покупатель',
                'ordering': ('name',),
            },
        ),
    ]
