# Generated by Django 5.0.3 on 2024-04-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Проданный товар', 'verbose_name_plural': 'Проданные товары'},
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
    ]
