# Generated by Django 5.0.3 on 2024-04-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Способ достаки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Способ оплаты',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_carts', to='catalog.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_carts', to='catalog.product')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.delivery', verbose_name='Способ доставки')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.payment', verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
