# Generated by Django 5.0.3 on 2024-04-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзина'},
        ),
    ]
